# WIS Custom Abilities — Auto-generated by BuilderAbility
# Este directorio contiene habilidades generadas dinamicamente por WIS.
# No editar manualmente a menos que sepas lo que haces.
# Los archivos aqui son creados/actualizados por WIS en tiempo de ejecucion.
